### ISSUE TITLE
redmine 5.0.2 ruby 3.1.2

### ISSUE THREAD

**Issue by ashrafalzyoud** [clear-code/redmine_full_text_search#104]
its support?
`How to recover broken database` if maybe broken my database tell me because i have important data

**Comment by komainu8** [comment]
Could you let me make sure of a couple of things?

1. Which are you use PostgreSQL or MySQL(or MariaDB) in your Redmine?
2. Currently, what problems have you run into your Redmine?
(What makes you think broken database?)

**Comment by ashrafalzyoud** [comment]
1-MySQL 
2- I'm see in your details
If database broken
I'm afraid if I'm install it,lose my datA 
---if u tell what the way for broken?!?
2- I'm using redmine 5.0.2 and there searching by text
What your plugin give more ?!?!

**Comment by kou** [comment]
This plugin supports Redmine 5.0.2 + Ruby 3.1.2 combination.

This plugin doesn't change Redmine's data. So this plugin doesn't break Redmine's data. But data for this plugin may be broken by MySQL crash. You can recover from the case because Redmine's data isn't broken even when the case is happen. See also how to recover from the case:  https://github.com/clear-code/redmine_full_text_search#how-to-recover-broken-database

If you need further information, you need to provide the followings:

* Command lines what you ran
* Error messages/logs/screenshots that show your problem
